SINGLE_LINE_WIDTH = 5.2
DOUBLE_LINE_WIDTH = 6.1
HALF_COURT_LINE_HEIGHT = 6.7 
SERVICE_LINE_WIDTH = 3.96 
DOUBLE_ALLY_WIDTH = 1.46
NO_MANS_LAND_HEIGHT = 0.76

PLAYER_1_HEIGHT_METERS = 1.6
PLAYER_2_HEIGHT_METERS = 1.6